---
version: "3.8"

services:
  main:
    image: ghcr.io/inko-lang/inko
    volumes:
      - ".:/aoc"
    working_dir: /aoc
    entrypoint: /bin/sh -c
    command:
      - "inko build --opt aggressive -o /tmp/aoc-main src/main.inko && /tmp/aoc-main"
