---
version: "3.8"

services:
  main:
    build:
      context: .
    volumes:
      - ".:/data"
    working_dir: /data
    entrypoint: /bin/sh -c
    command:
      - "cobc -o /main -free -x main.cbl parse-input.cbl parse-node.cbl part1.cbl part2.cbl && /main"
